name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ORG: devroom01
  IMAGE: dh-java-app
  TAG: 1.0.1    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE:$TAG

    - name: Docker Push to Docker Hub
      run: |
          docker tag $IMAGE:$TAG $DOCKER_ORG/$IMAGE:$TAG
          docker push $DOCKER_ORG/$IMAGE:$TAG
